### PR TITLE
JDCP-28 Enable Configuring of Reconnect Attempts and Delays

### PR DESCRIPTION
**Pull request by amoudi87**
This change enables configuration of reconnect attempts and number of retries for both DCP channels and Configuration Provider.
In addition, it stops attempts to reconnect once the conductor.stop() has been called.

The client interface must have CompleteHandler and ErrorHandler for the client to be able to deliver terminal errors and normal end of stream events.

### CODE REVIEW

**Comment by daschl** [comment]
@amoudi87 I think its good to make those values configurable, but here is some input:
- in the change i don't see where the config provider settings are used, and also I think it might be better to not configure the attempts at all, since shouldn't it be: try forever until a certain condition hits? for the config provider its: shutdown and for the dcp channels its: channel is not part of the server config anymore. Since what would you do if the attempts run out but the node is still part of the config?

**Comment by amoudi87** [comment]
@daschl 
Check out HttpStreamingConfigProvider. The config provider settings are used there but there was no way for the client user to configure those. I just enabled that.

For the dcp channels, attempt until the node is not part of the config doesn't work since we get into situations where we disconnect but the dcp channel keeps trying to connect and fail forever, with no way to stop it.

**Comment by avsej** [comment]
@amoudi87 does this change have JDCP ticket associated?

**Review by avsej — APPROVED** [review]

**Comment by amoudi87** [comment]
@avsej This fixes JDCP-28. How do we associate the commit with the ticket?

**Comment by avsej** [comment]
@amoudi87 could you put it into the commit message title?

**Comment by amoudi87** [comment]
Done. I don't think I have write access to this repo.
Also, It is crucial that we have something similar to onError and OnComplete for the client since we might get some terminal events/errors.

But that would be in a subsequent change

**Pull request merged**
